version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: unless-stopped
    networks:
      - scriptoryum-network

networks:
  scriptoryum-network:
    driver: bridge