-- public.asp_net_roles definição

-- Drop table

-- DROP TABLE public.asp_net_roles;

CREATE TABLE public.asp_net_roles (
	id text NOT NULL,
	"name" varchar(256) NULL,
	normalized_name varchar(256) NULL,
	concurrency_stamp text NULL,
	CONSTRAINT p_k_asp_net_roles PRIMARY KEY (id)
);
CREATE UNIQUE INDEX role_name_index ON public.asp_net_roles USING btree (normalized_name);


-- public.asp_net_users definição

-- Drop table

-- DROP TABLE public.asp_net_users;

CREATE TABLE public.asp_net_users (
	id text NOT NULL,
	user_name varchar(256) NULL,
	normalized_user_name varchar(256) NULL,
	email varchar(256) NULL,
	normalized_email varchar(256) NULL,
	email_confirmed bool NOT NULL,
	password_hash text NULL,
	security_stamp text NULL,
	concurrency_stamp text NULL,
	phone_number text NULL,
	phone_number_confirmed bool NOT NULL,
	two_factor_enabled bool NOT NULL,
	lockout_end timestamptz NULL,
	lockout_enabled bool NOT NULL,
	access_failed_count int4 NOT NULL,
	CONSTRAINT p_k_asp_net_users PRIMARY KEY (id)
);
CREATE INDEX email_index ON public.asp_net_users USING btree (normalized_email);
CREATE UNIQUE INDEX user_name_index ON public.asp_net_users USING btree (normalized_user_name);


-- public.a_i_configurations definição

-- Drop table

-- DROP TABLE public.a_i_configurations;

CREATE TABLE public.a_i_configurations (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id text NULL,
	max_tokens text DEFAULT '4000'::text NULL,
	temperature text DEFAULT '0.7'::text NULL,
	default_provider text NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT p_k_a_i_configurations PRIMARY KEY (id),
	CONSTRAINT f_k_a_i_configurations_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX i_x_a_i_configurations_user_id ON public.a_i_configurations USING btree (user_id);


-- public.a_i_provider_configs definição

-- Drop table

-- DROP TABLE public.a_i_provider_configs;

CREATE TABLE public.a_i_provider_configs (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	a_i_configuration_id int4 NOT NULL,
	provider text NOT NULL,
	api_key varchar(200) NOT NULL,
	selected_model varchar(100) NOT NULL,
	is_enabled bool DEFAULT true NOT NULL,
	last_test_result bool NULL,
	last_test_message varchar(500) NULL,
	last_tested_at timestamptz NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT p_k_a_i_provider_configs PRIMARY KEY (id),
	CONSTRAINT f_k_a_i_provider_configs_a_i_configurations_a_i_configuration_i FOREIGN KEY (a_i_configuration_id) REFERENCES public.a_i_configurations(id) ON DELETE CASCADE
);
CREATE INDEX i_x_a_i_provider_configs_a_i_configuration_id ON public.a_i_provider_configs USING btree (a_i_configuration_id);


-- public.asp_net_role_claims definição

-- Drop table

-- DROP TABLE public.asp_net_role_claims;

CREATE TABLE public.asp_net_role_claims (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	role_id text NOT NULL,
	claim_type text NULL,
	claim_value text NULL,
	CONSTRAINT p_k_asp_net_role_claims PRIMARY KEY (id),
	CONSTRAINT f_k_asp_net_role_claims_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES public.asp_net_roles(id) ON DELETE CASCADE
);
CREATE INDEX i_x_asp_net_role_claims_role_id ON public.asp_net_role_claims USING btree (role_id);


-- public.asp_net_user_claims definição

-- Drop table

-- DROP TABLE public.asp_net_user_claims;

CREATE TABLE public.asp_net_user_claims (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id text NOT NULL,
	claim_type text NULL,
	claim_value text NULL,
	CONSTRAINT p_k_asp_net_user_claims PRIMARY KEY (id),
	CONSTRAINT f_k_asp_net_user_claims_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE CASCADE
);
CREATE INDEX i_x_asp_net_user_claims_user_id ON public.asp_net_user_claims USING btree (user_id);


-- public.asp_net_user_logins definição

-- Drop table

-- DROP TABLE public.asp_net_user_logins;

CREATE TABLE public.asp_net_user_logins (
	login_provider text NOT NULL,
	provider_key text NOT NULL,
	provider_display_name text NULL,
	user_id text NOT NULL,
	CONSTRAINT p_k_asp_net_user_logins PRIMARY KEY (login_provider, provider_key),
	CONSTRAINT f_k_asp_net_user_logins_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE CASCADE
);
CREATE INDEX i_x_asp_net_user_logins_user_id ON public.asp_net_user_logins USING btree (user_id);


-- public.asp_net_user_roles definição

-- Drop table

-- DROP TABLE public.asp_net_user_roles;

CREATE TABLE public.asp_net_user_roles (
	user_id text NOT NULL,
	role_id text NOT NULL,
	CONSTRAINT p_k_asp_net_user_roles PRIMARY KEY (user_id, role_id),
	CONSTRAINT f_k_asp_net_user_roles_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES public.asp_net_roles(id) ON DELETE CASCADE,
	CONSTRAINT f_k_asp_net_user_roles_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE CASCADE
);
CREATE INDEX i_x_asp_net_user_roles_role_id ON public.asp_net_user_roles USING btree (role_id);


-- public.asp_net_user_tokens definição

-- Drop table

-- DROP TABLE public.asp_net_user_tokens;

CREATE TABLE public.asp_net_user_tokens (
	user_id text NOT NULL,
	login_provider text NOT NULL,
	"name" text NOT NULL,
	value text NULL,
	CONSTRAINT p_k_asp_net_user_tokens PRIMARY KEY (user_id, login_provider, name),
	CONSTRAINT f_k_asp_net_user_tokens_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE CASCADE
);


-- public.documents definição

-- Drop table

-- DROP TABLE public.documents;

CREATE TABLE public.documents (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	processed_file_name varchar(500) NOT NULL,
	description varchar(2000) NULL,
	storage_provider text NOT NULL,
	storage_path varchar(1000) NOT NULL,
	file_type text NOT NULL,
	uploaded_by_user_id text NULL,
	uploaded_at timestamptz DEFAULT now() NOT NULL,
	status text DEFAULT 'Uploaded'::text NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	text_extracted text NULL,
	original_file_name varchar(500) DEFAULT ''::character varying NOT NULL,
	file_size int8 DEFAULT 0 NOT NULL,
	summary text DEFAULT ''::text NULL,
	processing_started_at timestamptz NULL,
	CONSTRAINT p_k_documents PRIMARY KEY (id),
	CONSTRAINT f_k_documents_asp_net_users_uploaded_by_user_id FOREIGN KEY (uploaded_by_user_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT
);
CREATE INDEX i_x_documents_uploaded_by_user_id ON public.documents USING btree (uploaded_by_user_id);


-- public.extracted_entities definição

-- Drop table

-- DROP TABLE public.extracted_entities;

CREATE TABLE public.extracted_entities (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	document_id int4 NOT NULL,
	entity_type text NOT NULL,
	value varchar(500) NOT NULL,
	confidence_score numeric(5, 4) NOT NULL,
	context_excerpt varchar(1000) NULL,
	start_position int4 NULL,
	end_position int4 NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT p_k_extracted_entities PRIMARY KEY (id),
	CONSTRAINT f_k_extracted_entities_documents_document_id FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE CASCADE
);
CREATE INDEX i_x_extracted_entities_document_id ON public.extracted_entities USING btree (document_id);


-- public.insights definição

-- Drop table

-- DROP TABLE public.insights;

CREATE TABLE public.insights (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	document_id int4 NOT NULL,
	category text NOT NULL,
	description varchar(1000) NOT NULL,
	importance_level text NOT NULL,
	extracted_text varchar(2000) NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT p_k_insights PRIMARY KEY (id),
	CONSTRAINT f_k_insights_documents_document_id FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE CASCADE
);
CREATE INDEX i_x_insights_document_id ON public.insights USING btree (document_id);


-- public.risks_detected definição

-- Drop table

-- DROP TABLE public.risks_detected;

CREATE TABLE public.risks_detected (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	document_id int4 NOT NULL,
	description varchar(1000) NOT NULL,
	risk_level text NOT NULL,
	confidence_score numeric(5, 4) NOT NULL,
	evidence_excerpt varchar(2000) NULL,
	detected_at timestamptz DEFAULT now() NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT p_k_risks_detected PRIMARY KEY (id),
	CONSTRAINT f_k_risks_detected_documents_document_id FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE CASCADE
);
CREATE INDEX i_x_risks_detected_document_id ON public.risks_detected USING btree (document_id);


-- public.timeline_events definição

-- Drop table

-- DROP TABLE public.timeline_events;

CREATE TABLE public.timeline_events (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	document_id int4 NOT NULL,
	event_date timestamptz NOT NULL,
	event_type text NOT NULL,
	description varchar(1000) NOT NULL,
	source_excerpt varchar(2000) NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT p_k_timeline_events PRIMARY KEY (id),
	CONSTRAINT f_k_timeline_events_documents_document_id FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE CASCADE
);
CREATE INDEX i_x_timeline_events_document_id ON public.timeline_events USING btree (document_id);


-- public.chat_sessions definição

-- Drop table

-- DROP TABLE public.chat_sessions;

CREATE TABLE public.chat_sessions (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id text NULL,
	title varchar(200) NOT NULL,
	description varchar(500) NULL,
	document_id int4 NULL,
	message_count int4 DEFAULT 0 NOT NULL,
	last_activity_at timestamptz DEFAULT now() NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT p_k_chat_sessions PRIMARY KEY (id),
	CONSTRAINT f_k_chat_sessions_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES public.asp_net_users(id) ON DELETE CASCADE,
	CONSTRAINT f_k_chat_sessions_documents_document_id FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE SET NULL
);
CREATE INDEX i_x_chat_sessions_document_id ON public.chat_sessions USING btree (document_id);
CREATE INDEX i_x_chat_sessions_user_id ON public.chat_sessions USING btree (user_id);


-- public.document_chunks definição

-- Drop table

-- DROP TABLE public.document_chunks;

CREATE TABLE public.document_chunks (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	document_id int4 NOT NULL,
	chunk_index int4 NOT NULL,
	"content" text NULL,
	embedding public.vector NULL,
	created_at timestamptz NOT NULL,
	CONSTRAINT p_k_document_chunks PRIMARY KEY (id),
	CONSTRAINT f_k_document_chunks_documents_document_id FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE CASCADE
);
CREATE INDEX "IX_document_chunks_embedding" ON public.document_chunks USING ivfflat (embedding);
CREATE INDEX i_x_document_chunks_document_id ON public.document_chunks USING btree (document_id);


-- public.chat_messages definição

-- Drop table

-- DROP TABLE public.chat_messages;

CREATE TABLE public.chat_messages (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	chat_session_id int4 NOT NULL,
	"role" text NOT NULL,
	"content" text NOT NULL,
	document_id int4 NULL,
	document_name varchar(500) NULL,
	token_count int4 NULL,
	"cost" numeric(10, 6) NULL,
	a_i_provider text NULL,
	model_used varchar(100) NULL,
	response_time_ms int4 NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT p_k_chat_messages PRIMARY KEY (id),
	CONSTRAINT f_k_chat_messages_chat_sessions_chat_session_id FOREIGN KEY (chat_session_id) REFERENCES public.chat_sessions(id) ON DELETE CASCADE,
	CONSTRAINT f_k_chat_messages_documents_document_id FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE SET NULL
);
CREATE INDEX i_x_chat_messages_chat_session_id ON public.chat_messages USING btree (chat_session_id);
CREATE INDEX i_x_chat_messages_document_id ON public.chat_messages USING btree (document_id);