-- public.asp_net_users definição

-- Drop table

-- DROP TABLE public.asp_net_users;

CREATE TABLE public.asp_net_users (
	id text NOT NULL,
	user_name varchar(256) NULL,
	normalized_user_name varchar(256) NULL,
	email varchar(256) NULL,
	normalized_email varchar(256) NULL,
	email_confirmed bool NOT NULL,
	password_hash text NULL,
	security_stamp text NULL,
	concurrency_stamp text NULL,
	phone_number text NULL,
	phone_number_confirmed bool NOT NULL,
	two_factor_enabled bool NOT NULL,
	lockout_end timestamptz NULL,
	lockout_enabled bool NOT NULL,
	access_failed_count int4 NOT NULL,
	CONSTRAINT p_k_asp_net_users PRIMARY KEY (id)
);
CREATE INDEX email_index ON public.asp_net_users USING btree (normalized_email);
CREATE UNIQUE INDEX user_name_index ON public.asp_net_users USING btree (normalized_user_name);


-- public.documents definição

-- Drop table

-- DROP TABLE public.documents;

CREATE TABLE public.documents (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	processed_file_name varchar(500) NOT NULL,
	description varchar(2000) NULL,
	storage_provider text NOT NULL,
	storage_path varchar(1000) NOT NULL,
	file_type text NOT NULL,
	uploaded_by_user_id text NULL,
	uploaded_at timestamptz DEFAULT now() NOT NULL,
	status text DEFAULT 'Uploaded'::text NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	text_extracted text NULL,
	original_file_name varchar(500) DEFAULT ''::character varying NOT NULL,
	file_size int8 DEFAULT 0 NOT NULL,
	summary text DEFAULT ''::text NULL,
	processing_started_at timestamptz NULL,
	CONSTRAINT p_k_documents PRIMARY KEY (id),
	CONSTRAINT f_k_documents_asp_net_users_uploaded_by_user_id FOREIGN KEY (uploaded_by_user_id) REFERENCES public.asp_net_users(id) ON DELETE RESTRICT
);
CREATE INDEX i_x_documents_uploaded_by_user_id ON public.documents USING btree (uploaded_by_user_id);


-- public.document_chunks definição

-- Drop table

-- DROP TABLE public.document_chunks;

CREATE TABLE public.document_chunks (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	document_id int4 NOT NULL,
	chunk_index int4 NOT NULL,
	"content" text NULL,
	embedding public.vector NULL,
	created_at timestamptz NOT NULL,
	CONSTRAINT "PK_document_chunks" PRIMARY KEY (id),
	CONSTRAINT "FK_document_chunks_documents_document_id" FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE CASCADE
);
CREATE INDEX "IX_document_chunks_document_id" ON public.document_chunks USING btree (document_id);
CREATE INDEX "IX_document_chunks_embedding" ON public.document_chunks USING ivfflat (embedding);